In [1]:
import cv2

In [2]:
import numpy as np

In [3]:
laplacian = []

In [4]:
laplacian.append(np.zeros((5,5),dtype=np.uint8))

In [5]:
laplacian[0]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [6]:
laplacian[0][2,2] = 255

In [7]:
laplacian[0]

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0, 255,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=uint8)

In [8]:
#A = cv2.imread('lena.png')

In [9]:
#A

In [10]:
print(type(laplacian[0]))

<class 'numpy.ndarray'>


In [11]:
for i in range(5):
    interpolation = cv2.pyrUp(laplacian[i])
    laplacian.append(interpolation)

In [12]:
laplacian[0]

array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0, 255,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=uint8)

In [13]:
laplacian[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   4,  16,  24,  16,   4,   0,   0,   0],
       [  0,   0,  16,  64,  96,  64,  16,   0,   0,   0],
       [  0,   0,  24,  96, 143,  96,  24,   0,   0,   0],
       [  0,   0,  16,  64,  96,  64,  16,   0,   0,   0],
       [  0,   0,   4,  16,  24,  16,   4,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=uint8)

In [14]:
laplacian[2]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   1,   2,   3,   3,   3,   2,   1,   1,
          0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   1,   3,   5,   8,  10,  11,  10,   8,   5,   3,
          1,   0,   0,   0,   0,   0,   0],
       [  0,   0,   1,   3,   6,  13,  19,  25,  28,  25,  19,  13,   6,
          3,   1,   0,   0,   0,   0,   0],
       [  0,   0,   1,   5,  13,  25,  39,  50,  55,  50,  39,  25,  13,
          5,   1,   0,   0,   0,   0,   0],
       [  0,   0,   2,   8,  19,  39,  60,  77,  85,  77,  60,  39,  19,
          8,   2,   0,   0,   0,   0,   0],
       [  0,   0,   3,  10,  25,  50,  77, 100, 110, 100,  77,  50,  25,
         10,   3,   0,   0,   0,   0,   0],
       [  0,   0,   3,  11,  28,  55,  85, 110, 120, 110,  85,  

In [15]:
laplacian[0].sum()

255

In [16]:
laplacian[1].sum()

1023